#!/bin/bash
die () {
    echo $@
    exit 1
}
[ $# -gt 3 -o $# -eq 0 ] && die "usage: $0 <file> [mv/to/dir/ [link/to/dir/]]"
[ $# -ge 3 ] && link_dir="$3" || link_dir="$HOME/Desktop"
[ $# -ge 2 ] && mv_dir="$2"   || mv_dir="$HOME/doc"
filepath="$1"
filename="${1##*/}"
[ -d "$link_dir" ] || die "ERROR: link_dir $link_dir does not exist."
[ -d "$mv_dir"   ] || die "ERROR: mv_dir $mv_dir does not exist."
[ -f "$filepath" ] || die "ERROR: $filepath does not exist, or not a file."
echo "mv $filepath $mv_dir && ln -s $mv_dir/$filename $link_dir/"
read -p "Press Enter to continue, other to abort."
[ x"$REPLY" = x"" ] || die "USER QUIT."
mv "$filepath" "$mv_dir" && ln -s "$mv_dir/$filename" "$link_dir/"
echo "Jobs done. More work?"

